#服务器相关配置
server:
  port: 8888
  servlet:
    context-path: /
#mysql相关配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tthome
    url: jdbc:mysql://192.168.90.253:3306/check_data?characterEncoding=utf-8&useSSL=false
 #MyBatis相关配置
mybatis:
  mapper-locations: classpath:mappers/*.xml

 #二维码存储路径
img:
  path: D:\QRcode\

  #二维码访问链接
qrcode:
  url: http://visney.cn:8888/result.html?key=
