#服务器相关配置
server:
  port: 9999
  servlet:
    context-path: /
#mysql相关配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/check?characterEncoding=utf-8&useSSL=false
 #MyBatis相关配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
